Create Profile
TarasKarabas/First_project pull request #1
Opened 2022-04-02 00:28 UTC by TarasKarabas

Upgrade prifile

2022-04-02 02:46 UTC, Alexdive requested changes
Good job with constraints.

2022-04-02 02:46 UTC, Alexdive commented on First_project/First_project/AuxiliaryElements/AppConstants.swift
> +enum UppConstants{
AppConstants

2022-04-02 02:46 UTC, Alexdive commented on First_project/First_project/AuxiliaryElements/Extensions.swift
> +extension SViewController: UISearchBarDelegate {
You can keep extensions to classes in the same class with file

2022-04-02 02:46 UTC, Alexdive commented on First_project/First_project/Profile/ProfileHeaderView.swift
> +        profilePicture.layer.cornerRadius = 100 / 2
You can make additional var in the class with the profilePicture width or height and then use it here and in the constraints

2022-04-02 02:46 UTC, Alexdive commented on First_project/First_project/Profile/ProfileViewController.swift
> +        profileHeader.frame = CGRect(x: 0, y: 143, width: view.bounds.width, height:  300)
Why do you use frames instead of constraints? Better to stick with one approach.

2022-04-02 02:46 UTC, Alexdive commented on First_project/First_project/Profile/ShareViewController.swift
> +//extension UIView {
You can delete unneeded code

2022-04-02 02:46 UTC, Alexdive commented on First_project/First_project/Search/SViewController.swift
> +//extension SViewController: UISearchBarDelegate {
Better leave this extension here

2022-04-02 02:46 UTC, Alexdive commented on First_project/First_project/Search/SViewController.swift
> +//extension SViewController: UISearchBarDelegate {
And also SViewController is not good naming. Make it self descriptive.
Same for FViewController

2022-04-04 03:25 UTC, TarasKarabas commented
Corrected all remarks

2022-04-04 03:25 UTC, merged